import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Router from "next/router";
import { useState } from "react";
import { isPropertyAccessOrQualifiedName } from "typescript";
import { PlanetI, PlanetsI } from "../model/Planets";
import styles from "../styles/Home.module.css";
import { GetStaticPaths } from "next";
import Link from "next/link";

const API_URL = "https://swapi.dev/api/";
interface HomeComponentProps {
  data: PlanetsI;
  page: number;
}

const Home: NextPage<HomeComponentProps> = ({ data, page }) => {
  // const pages = Math.ceil(data.count / 10);

  // const handleNextClick = () => {
  //   if (page < pages) {
  //     Router.push(`/?page=${page + 1}`);
  //   }
  // };

  // const handlePageClick = (event: any) => {
  //   console.log(event.target.id);
  //   Router.push(`/?page=${event.target.id}`);
  // };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/planets/1">PLANETS</Link>
      {/* {page < pages && <button onClick={handleNextClick}>next page</button>}
      <button onClick={() => handlePageClick(event)} id={`1`}>
        1
      </button>

      <main className={styles.main}>
        {data.results.map(({ name }) => (
          <h1 key={`${name}`}>{name}</h1>
        ))}
      </main> */}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

// export const getStaticPaths: GetStaticPaths = async () => {
//   return {
//     paths: [
//       { params: { page: 1 } },
//       { params: { page: 2 } },
//       { params: { page: 3 } },
//       { params: { page: 4 } },
//       { params: { page: 5 } },
//       { params: { page: 6 } },
//       // See the "paths" section below
//     ],
//     fallback: false, // See the "fallback" section below
//   };
// }

// export const getStaticProps = async ({ params: { page = 1 } }) => {
//   const respone = await fetch(`${API_URL}/planets/?page=${page}`);
//   const data = await respone.json();
//   return {
//     data,
//     page: +page,
//   };
// };

export default Home;
